// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceDay_Event_Management.API.Data;

#nullable disable

namespace RaceDay_Event_Management.API.Data.Migrations
{
    [DbContext(typeof(RaceDayDbContext))]
    [Migration("20261008125827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<decimal?>("CategoryDistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumParticipants")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("EventId");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_Age", "[MinimumAge] IS NULL OR [MinimumAge] >= 0");

                            t.HasCheckConstraint("CK_Categories_MaxAge", "[MaximumAge] IS NULL OR [MaximumAge] >= [MinimumAge]");

                            t.HasCheckConstraint("CK_Categories_Participants", "[MaximumParticipants] IS NULL OR [MaximumParticipants] > 0");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Enrolment", b =>
                {
                    b.Property<int>("EnrolmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolmentId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("EnrolmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId", "EventId")
                        .IsUnique();

                    b.ToTable("Enrolments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrolments_Status", "[Status] IN ('Pending', 'Confirmed', 'Cancelled', 'Completed')");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("OrganiserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegistrationDeadline")
                        .HasColumnType("date");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_Distance", "[DistanceKm] > 0");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.EventImage", b =>
                {
                    b.Property<int>("EventImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventImageId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("EventImageId");

                    b.HasIndex("EventId");

                    b.ToTable("EventImages", (string)null);
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("EventTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("EventTypes", (string)null);
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("EnrolmentId")
                        .HasColumnType("int");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("FinishTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrolmentId")
                        .IsUnique();

                    b.ToTable("Results", null, t =>
                        {
                            t.HasCheckConstraint("CK_Results_Position", "[FinishPosition] > 0");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Organiser', 'Participant')");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.WeatherSnapshot", b =>
                {
                    b.Property<int>("WeatherSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherSnapshotId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FeelsLikeCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("HumidityPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("WeatherCondition")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("WindSpeedKmh")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("WeatherSnapshotId");

                    b.HasIndex("EventId");

                    b.ToTable("WeatherSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_Weather_Humidity", "[HumidityPercentage] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Category", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.Event", "Event")
                        .WithMany("Categories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Enrolment", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.Category", "Category")
                        .WithMany("Enrolments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay_Event_Management.API.Models.Event", "Event")
                        .WithMany("Enrolments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay_Event_Management.API.Models.User", "Participant")
                        .WithMany("Enrolments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Event", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay_Event_Management.API.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay_Event_Management.API.Models.User", "Organiser")
                        .WithMany("OrganisedEvents")
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Location");

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.EventImage", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Result", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.Enrolment", "Enrolment")
                        .WithOne("Result")
                        .HasForeignKey("RaceDay_Event_Management.API.Models.Result", "EnrolmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrolment");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.WeatherSnapshot", b =>
                {
                    b.HasOne("RaceDay_Event_Management.API.Models.Event", "Event")
                        .WithMany("WeatherSnapshots")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Category", b =>
                {
                    b.Navigation("Enrolments");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Enrolment", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Event", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Enrolments");

                    b.Navigation("Images");

                    b.Navigation("WeatherSnapshots");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.Location", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RaceDay_Event_Management.API.Models.User", b =>
                {
                    b.Navigation("Enrolments");

                    b.Navigation("OrganisedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
